{% set name = "macholib" %}
{% set version = "1.16.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f408c93ab2e995cd2c46e34fe328b130404be143469e41bc366c807448979362

build:
  entry_points:
    - macho_find = macholib.macho_find:main
    - macho_standalone = macholib.macho_standalone:main
    - macho_dump = macholib.macho_dump:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - altgraph >=0.17

{% set deselect_tests = "" %}
# This package is platform independent but some test are platform dependent, those work only on macOS
{% set deselect_tests = deselect_tests + " --deselect=macholib_tests/test_command_line.py::TestCmdLine::test_check_file" %}
{% set deselect_tests = deselect_tests + " --deselect=macholib_tests/test_command_line.py::TestCmdLine::test_macho_dump" %}
{% set deselect_tests = deselect_tests + " --deselect=macholib_tests/test_command_line.py::TestCmdLine::test_shared_main" %}
{% set deselect_tests = deselect_tests + " --deselect=macholib_tests/test_dyld.py::TestDyld::test_dyld_find" %}
{% set deselect_tests = deselect_tests + " --deselect=macholib_tests/test_dyld.py::TestDyld::test_framework_find" %}
{% set deselect_tests = deselect_tests + " --deselect=macholib_tests/test_dyld.py::TestTrivialDyld::testBasic" %}

test:
  source_files:
    - macholib_tests
    - setup.cfg
  imports:
    - macholib
  requires:
    - pip
    - pytest
    - setuptools
  commands:
    - pip check
    - macho_dump --help
    - pytest -v macholib_tests {{ deselect_tests }}

about:
  home: https://github.com/ronaldoussoren/macholib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Mach-O header analysis and editing
  description: |
    macholib can be used to analyze and edit Mach-O headers,
    the executable format used by Mac OS X.
  doc_url: https://macholib.readthedocs.io
  dev_url: https://github.com/ronaldoussoren/macholib

extra:
  recipe-maintainers:
    - rth
