{% set name = "macholib" %}
{% set version = "1.9" %}
{% set sha256 = "9aeec52d7da59912b15445d08b08d95cee48414f01dd035be06f04a825973c08" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - altgraph >=0.15

test:
  imports:
    - macholib
  commands:
    - python -m macholib find /tmp/

about:
  home: http://bitbucket.org/ronaldoussoren/macholib
  license: MIT
  license_family: MIT
  # the licence file is missing in this package
  # https://bitbucket.org/ronaldoussoren/macholib/issues/22/license-file
  summary: 'Mach-O header analysis and editing'
  description: |
      macholib can be used to analyze and edit Mach-O headers,
      the executable format used by Mac OS X.
  doc_url: https://macholib.readthedocs.io/en/latest/
  dev_url: http://bitbucket.org/ronaldoussoren/macholib

extra:
  recipe-maintainers:
    - rth
