travis:
  secure:
    BINSTAR_TOKEN: klvc5PoVwppqN7PO7GNQDlafQ3aZtMoDJok889s0OES38/Ln92w4N9i3nqHtn8ybbMxL8FPRqf1kWSAJoBv0NWBfRLYd3vYjSiwEiQN5h5wk2+weebvGvJu2xD8Na9B7fu7C5OmGyeNVqz9RH+caZUCZjOSncUPtsTQC21HR1UvEcnB2CwOUC9J5dXcYIl/PXmGu0i5I6qcPa4v93qS64Cdzj9pp/uo/NBZ2ceX68ci661VlnFfXiv/tXh2gXPDXP9LVkupPPCKU9/KxazGI47242yDNKauP6AdoXMbe4wRCNHiMDBNNqx8TG7fHCQ6XiKWE0wbfkY279lcHLpNZLW27urk657hXaS5SJWE5aGbpNqBXBgrZahnpiGfPRH0eQDN5z1u3F77iVPPrlnz8vReJGvviVjpGZno/iQkiHJyud+zAS16b7hWaDJAtfBw9gcSzwuxY0f4VTz8fraqokyrRWD3ABEe1VI2Zp2JyJmNSFtKe+QycGZysoVQqS9CiNIJqQlqvZBy+WtTEndlSoNAfdjKL9DlPGikTrkMgFe6NLCu6C4cIWPZAoK2emtqtLTYs4esW4qWi9L+JDrLyMjCBmcVIPBfRsc5fUPfEaTjbm0lMjAB8toWpk/OApvYlYDe8KZVpg6eEyf9VG5M5OXuQ5zpPDgtcudlZOVUV37g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
