travis:
  secure:
    BINSTAR_TOKEN: l+7E8i5DeEiyq5q382rzYOfhoWzXsX29EchyNGZh6PMmRP/kSR9zqSauLaCVkcuVoWsWvdYYDbYjYKbSYyrrjW9okj7HHbdhSXikfuWHO/CvxREYwNal8lSE4wVWrQYYV3xEK069ikt7ET7yDSAktPJt+8tvX7c4oooKOQqnFEFR33TG5HIfW9mKRCy2Urp/DjlWO4rS9qC2s6myPu7ct2H1Rhwig+x/UQRfRemipJtYJqfse0MlVW34NYM2rdhwaOG5QUR3uDoKzg/4iq07d8AXEKysri/TKybf/QPHSVrT+FotjcQf4zQzVJkJiI2KWl8Ea97ELFO+73kQqRnrAb9jVGbc9Z3eBsCS9CqlLHlnNgiSrK7dKofcfg85+/QpJ39h5y2pzpwueDhA57jJwTN+pv7m/hkUYZZKLzoig9x5lu4bRqDw6j3HhWz3+DtoryUmlMouqDkx3zUBEb6nvushmIApRLKuCFIXqRdtkgNaDL3mMfZ6oZ76tsQoiOiez/PfPn2pSx/huIitZe0UXBpSZUcn/SlU1zZwLnmJOc/HkPeRkVN1XMx/PmckwWRV6nrUi4UrdEWeMzhoDrZv3EuTOI+9nICvxRzsipfVAGDnBYv0Khtz6T81ZjdS/xK4AjpM4Rd3hBKO7Opef1RQTjYl1NmAn1fNQVt6wa9Pcx4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
