travis:
  secure:
    BINSTAR_TOKEN: agdQJA/c0jXHm7ek+2e3DuyG2csKxMhZzdrt7NCU1m1ibl9Ad5kVuRPwfexa15TBekga6IFm7/AIVR3XHiA5EtL3O2gZTWf7Mlu61rxuhxOnYoR8y/k5cyMide0cYQu2dcVAf0i4QOsaqOnJ9hsI0BlnDvXMCxRKzJoRWd5jWmIRDt55XUpFvQgvRoVlZdTlYSB8xp7UCZZJmBo5DW+Gc8C8bmd3FYmCINw5v7zuI4Os4y19PUcW4T26y/KIlCestBXcuwRDOwlDbdpGSDBDv+E9QnwQH7feDxr+N6hfavbhejmAbf23ug1aaexs2//kYe46aQrvySDLUh3rxHN7a0oRCxXAEarOSa6DP0ltfVbDurVIDkxUGg9rkdGXTiIBM4Om/F0kDk04fdLsmlRJB7KBx1KPXpwNjBqdms8H+FCCg5lDmZXuFvZSWCXOBnRxsY1QfSY5x7gqaiClQcUSRyfp5vx17VA3GGIpkn2ZzwGqk4THWXIjXAgzKCoBe1+TjD99j416ENDTiAtDtZ3sEL9oQKhXtoRIv8U1Aw1XYTMs7xWwCtWNc6RYxKsu73nUtbzaAVR5piCav4YSf56H3XZ575iMgTHWeMszVsXU8vEVhmngiUO5qp5SGIq0j+omQLQFWhPIRoeE8rBovXhjrlR1uTTBOY/cduzfjhRMutg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
